### ISSUE TITLE
Add example code for Cassandra graceful shutdown

### ISSUE THREAD

**Issue by gergelyke** [godaddy/terminus#19]

**Comment by lukaszewczak** [comment]
Hi @gergelyke ,

I never worked with Cassandra but after some research I found that I can check if some host(s) from Cassandra cluster is up by using example like this (based on https://stackoverflow.com/questions/44501087/checking-health-of-all-cassandra-nodes):

```javascript
"use strict";
const cassandra = require('cassandra-driver');

const client = new cassandra.Client({ contactPoints: ['127.0.0.1'] });
client.connect()
  .then(function () {
    console.log('Connected to cluster with %d host(s): %j', client.hosts.length);
    const activeHosts = [];
    client.hosts.forEach(function (host) {
      if ( host.isUp() ) {
         activeHosts.push(host);
      }
    });
    const isHealth = client.hosts.length === activeHosts.length; //?
    console.log('Shutting down');
    return client.shutdown();
  })
  .catch(function (err) {
    console.error('There was an error when connecting', err);
    return client.shutdown();
  });
```

When we can assume that Cassandra cluster is health? When all hosts in cluster are up or at least one host in cluster is up?

**Comment by gergelyke** [comment]
@jcrugzz any chance you can help us out here?

**Comment by lukaszewczak** [comment]
Hi @gergelyke , do you have any thoughts on this topic? Maybe we can add possibility to change default success response for healthcheck, and in this situation we can just return object with status about every cassandra host?

**Comment by jcrugzz** [comment]
@lukaszewczak @gergelyke I'm not sure we need to get into the weeds and check anything about the Cassandra hosts to determine health. That can be useful data in some circumstances for monitoring a cluster and network connectivity but I think you are better off running a query and retrieving data as that is a more real health test. Just because you are connected to at least one node doesn't mean you can read its data off disk. Also there is a lot of variation in requirements depending on the level of consistency you want out of a query (i.e. some queries may only require 1 node to exist while others require quorum). These details end up up being application and data model specific.

**Comment by lukaszewczak** [comment]
OK, thank you @jcrugzz , it makes sense. I will work on PR for this

**Comment by gergelyke** [comment]
@lukaszewczak any chance you had the time to work on it? :)

**Comment by gergelyke** [comment]
no rush, take your time :) thanks a lot for the contributions so far!

**Comment by gergelyke** [comment]
Fixed in https://github.com/godaddy/terminus/pull/52
